# "$schema" = "https://mise.jdx.dev/schema/mise.json"
[env]
EGRESS_BUS_LOG_LEVEL = "debug"

[tools]
protoc = "latest"

[tasks]
[tasks.compile-protobufs]
description = "Compiles protobufs from definitions"
run = "./scripts/compile-protobufs.sh"

[tasks.update-submodules]
description = "Update contrib libs"
run = "git submodule update --recursive"
